---
title: "Ingest DOE Student Record Demographics"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## LOAD LIBRARIES AND FUNCTIONS
```{r load_libraries, warning=FALSE, message=FALSE}
library(data.table)
library(dataplumbr)
library(here)
library(inspectdf)
library(maditr)
```

## DOE Student Record Demographics
### Load data file
```{r cache=TRUE, message=FALSE}
doe_student_records <- fread(here("data/original/q5/DOE/Student Records.csv"), colClasses = "character")
```

### Standardize column names
```{r}
colnames(doe_student_records) <- name.standard_col_names(colnames(doe_student_records))
```

### Check if more than one record per unique_id and calendar_year
```{r}
multiples <- nrow(doe_student_records[, .N,.(unique_id, school_year)][N > 1])
multiples
```


### Apply Deduplication algorithm to get Demographics By Year
```{r}
doe_student_dmgs <- doe_student_records[, .(birth_month, birth_year, race_type, ethnic_flag, prek_funding_code),.(unique_id, school_year)]

set.dedup_choice <- function(df) {
    dt <- data.table::setDT(df)
    for (j in colnames(dt)) {
        data.table::set(dt, j = j, value = dt[get(j) != "", .N, j][order(-N)][, ..j][1])
    }
    dt[1]
}

set.dedup_choice_by_key <- function(df, key = "uid") {
    if (exists("out_dt") == TRUE) rm(out_dt, envir = globalenv())

    dt <- data.table::setDT(df)
    unique_keys <- unique(dt[, get(key)])
    key_cnt <- length(unique_keys)
    pb <- progress::progress_bar$new(format = "[:bar] :current/:total :percent eta: :eta", total = key_cnt)

    for (k in unique_keys) {
        pb$tick()
        g <- dt[get(key)==k]
        r <- set.dedup_choice(g)
        if (exists("out_dt") == FALSE) out_dt <- r else out_dt <- rbindlist(list(out_dt, r))
    }

    out_dt
}

doe_student_dmgs_dedup <- set.dedup_choice_by_key(doe_student_dmgs, "unique_id")

# verify only one code per id per year
nrow(doe_student_dmgs_dedup[, .N, .(unique_id)][N > 1])
```

### write to csv
```{r}
fwrite(doe_student_dmgs_dedup, here("data/working/DOE/doe_student_records_by_year_dmgs_prek.csv"))
```
