
```{r }
# Basic Demographic Longitudinal Inconsistencies
```

FUNCTIONS ----

```{r load_libraries, warning=FALSE, message=FALSE}
library(data.table)
library(dataplumbr)
library(tidycensus)
library(sf)
library(ggplot2)
library(here)
library(knitr)
library(kableExtra)
```

DSS RECORDS ----
Load DSS records and standardize column names

```{r dss_customers_load_rename, cache=TRUE, message=FALSE}
dss_customers_by_year <- fread(here("data/original/q4/DSS/DSS Customers By Year.csv"), colClasses = "character")
colnames(dss_customers_by_year) <- standard_col_names(colnames(dss_customers_by_year))
```

fix a misspelling for future joining

```{r fix_misspelling}
colnames(dss_customers_by_year)[colnames(dss_customers_by_year) == "calender_year_number"] <- "calendar_year_number"
```

find demographics that change when they shouldn't

```{r changing_dmgs}
gender_mutli <-
  dss_customers_by_year[age_group_code < 6 &
         !is.na(gender_code), length(unique(gender_code)), unique_id][V1 > 1, .N]
birth_year_mutli <-
  dss_customers_by_year[age_group_code < 6 &
         !is.na(year_of_birth), length(unique(year_of_birth)), unique_id][V1 > 1, .N]
birth_month_mutli <-
  dss_customers_by_year[age_group_code < 6 &
         !is.na(month_of_birth), length(unique(month_of_birth)), unique_id][V1 > 1, .N]
ethnicity_mutli <-
  dss_customers_by_year[age_group_code < 6 &
         !is.na(ethnicity_code) &
         ethnicity_code != 0, length(unique(ethnicity_code)), unique_id][V1 > 1, .N]
race_white_mutli <-
  dss_customers_by_year[age_group_code < 6 &
         !is.na(customer_race_is_white_indicator) &
         customer_race_is_white_indicator %in% c("Y", "N"), length(unique(customer_race_is_white_indicator)), unique_id][V1 > 1, .N]
race_black_mutli <-
  dss_customers_by_year[age_group_code < 6 &
         !is.na(customer_race_is_black_indicator) &
         customer_race_is_black_indicator %in% c("Y", "N"), length(unique(customer_race_is_black_indicator)), unique_id][V1 > 1, .N]

unique_n <- dss_customers_by_year[, .(unique_id), unique_id][, .N]
```

chart inconsistencies

```{r inconsistencies}
dmg_df <-
  data.frame(
    demographic = c(
      "gender",
      "birth_year",
      "birth_month",
      "ethnicity",
      "race_black",
      "race_white"
    ),
    multiples = c(
      100*(gender_mutli / unique_n),
      100*(birth_year_mutli / unique_n),
      100*(birth_month_mutli / unique_n),
      100*(ethnicity_mutli / unique_n),
      100*(race_black_mutli / unique_n),
      100*(race_white_mutli / unique_n)
    )
  )

ggplot(data=dmg_df, aes(x=demographic, y=multiples)) +
  geom_bar(stat = "identity") +
  ggtitle("Children with Inconsistent Demographic Entries")
```

